---
language: node_js
node_js:
  - "0.12"

sudo: false

cache:
  directories:
    - node_modules

env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-1.10.0
  - EMBER_TRY_SCENARIO=ember-1.10.1
  - EMBER_TRY_SCENARIO=ember-1.11.0
  - EMBER_TRY_SCENARIO=ember-1.11.1
  - EMBER_TRY_SCENARIO=ember-1.11.2
  - EMBER_TRY_SCENARIO=ember-1.11.3
  - EMBER_TRY_SCENARIO=ember-1.12.0
  - EMBER_TRY_SCENARIO=ember-1.12.1
  - EMBER_TRY_SCENARIO=ember-1.13.0
  - EMBER_TRY_SCENARIO=ember-1.13.1
  - EMBER_TRY_SCENARIO=ember-1.13.2
  - EMBER_TRY_SCENARIO=ember-1.13.3
  - EMBER_TRY_SCENARIO=ember-1.13.4
  - EMBER_TRY_SCENARIO=ember-1.13.5
  - EMBER_TRY_SCENARIO=ember-1.13.6
  - EMBER_TRY_SCENARIO=ember-1.13.7
  - EMBER_TRY_SCENARIO=ember-1.13.8
  - EMBER_TRY_SCENARIO=ember-1.13.9

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-1.13.0

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - ember try $EMBER_TRY_SCENARIO test
